# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_iban.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('currency', models.CharField(choices=[('Dollars', 'Dollars'), ('Euro', 'Euro'), ('Lira', 'Lira')], max_length=50, null=True)),
                ('account_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('iban', django_iban.fields.IBANField(enforce_database_constraint=True, max_length=34, unique=True)),
                ('account_no', django_iban.fields.IBANField(enforce_database_constraint=True, max_length=34, unique=True)),
                ('the_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('e_mail', models.CharField(max_length=300, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField(default=0)),
                ('loan_account', models.CharField(max_length=50, null=True)),
                ('loan_duration', models.IntegerField(default=24, null=True)),
                ('loan_interest', models.FloatField(default=0.05, null=True)),
                ('outstanding_loan', models.IntegerField(default=0, null=True)),
                ('loan_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=50, null=True)),
                ('receiver_name', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('the_amount', models.IntegerField(default=0)),
                ('account_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.Accounts')),
            ],
        ),
    ]
